export const SHOP_LIST_REQUEST = 'SHOP_LIST_REQUEST'
export const SHOP_LIST_SUCCESS = 'SHOP_LIST_SUCCESS'
export const SHOP_LIST_FAIL = 'SHOP_LIST_FAIL'

export const SHOP_DETAILS_REQUEST = 'SHOP_DETAILS_REQUEST'
export const SHOP_DETAILS_SUCCESS = 'SHOP_DETAILS_SUCCESS'
export const SHOP_DETAILS_FAIL = 'SHOP_DETAILS_FAIL'
export const SHOP_DETAILS_RESET = 'SHOP_DETAILS_RESET'

export const SHOP_DELETE_REQUEST = 'SHOP_DELETE_REQUEST'
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS'
export const SHOP_DELETE_FAIL = 'SHOP_DELETE_FAIL'

export const SHOP_CREATE_REQUEST = 'SHOP_CREATE_REQUEST'
export const SHOP_CREATE_SUCCESS = 'SHOP_CREATE_SUCCESS'
export const SHOP_CREATE_FAIL = 'SHOP_CREATE_FAIL'
export const SHOP_CREATE_RESET = 'SHOP_CREATE_RESET'

export const SHOP_UPDATE_REQUEST = 'SHOP_UPDATE_REQUEST'
export const SHOP_UPDATE_SUCCESS = 'SHOP_UPDATE_SUCCESS'
export const SHOP_UPDATE_FAIL = 'SHOP_UPDATE_FAIL'
export const SHOP_UPDATE_RESET = 'SHOP_UPDATE_RESET'

export const SELLER_SHOP_DETAILS_REQUEST = 'SELLER_SHOP_DETAILS_REQUEST'
export const SELLER_SHOP_DETAILS_SUCCESS = 'SELLER_SHOP_DETAILS_SUCCESS'
export const SELLER_SHOP_DETAILS_FAIL = 'SELLER_SHOP_DETAILS_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET'
