export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const DETAILS_REQUEST = 'DETAILS_REQUEST'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL = 'DETAILS_FAIL'
export const DETAILS_RESET = 'DETAILS_RESET'

export const UPDATE_DETAILS_REQUEST = 'UPDATE_DETAILS_REQUEST'
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS'
export const UPDATE_DETAILS_FAIL = 'UPDATE_DETAILS_FAIL'
export const UPDATE_DETAILS_RESET = 'UPDATE_DETAILS_RESET'

export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL'

export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST'
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS'
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL'
export const ADMIN_USER_UPDATE_RESET = 'ADMIN_USER_UPDATE_RESET'

export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST'
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS'
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL'
